### ISSUE TITLE
Not included in core

### ISSUE THREAD

**Issue by josephdadams** [bitfocus/companion-module-pixap-pixtimerpro#1]
@knicolas22 This module is not in either the backport 1.4 branch or the master 2.0 branch. How is it coming along? Is it ready to be included?

**Comment by knicolas22** [comment]
Hello,The module is finished, it is ready to be usedThank you





On Thu, Aug 29, 2019 at 2:45 AM +0200, "Joseph Adams" <notifications@github.com> wrote:












@knicolas22 This module is not in either the backport 1.4 branch or the master 2.0 branch. How is it coming along? Is it ready to be included?

**Comment by josephdadams** [comment]
We will get it included. Thank you!
