### ISSUE TITLE
piXtimerPro adding +/- minutes

### ISSUE THREAD

**Issue by 1080Productions** [bitfocus/companion-module-pixap-pixtimerpro#3]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
A clear and concise description of what the feature does

I would like there to be a way to add or take away a minute at a time while the timer is counting down.  You can take away or add minutes in the program but there isn't a way in companion to set up a button to do that.  It would be very helpful.

**Is this platform dependent (windows, mac, ..)?**
Explain.  I am using Mac but I don't think it matters.

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along.

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

If we are running behind schedule, it would allow me to take away minutes from a presentation so we can stay on time.

**Comment by josephdadams** [comment]
I transferred this to the pixtimerpro repository.

**Comment by 1080Productions** [comment]
Thank you.  I didn’t know exactly where to put it

Thank You,

Tony Habich
Owner, Video Engineer, Trucking and Logistics
502-741-2925
tony@1080-productions.com

www.1080-productions.com


On February 21, 2020 at 8:29:40 AM, Joseph Adams (notifications@github.com) wrote:

I transferred this to the pixtimerpro repository.

**Comment by knicolas22** [comment]
Hello 
The function was added in the version of piXtimer Pro 1.9.8, is in the companion module-piXap-piXtimerPro 1.0.6.
The module should be updated in the next update of companion
Thank You
